name: Build and Run Docker Image

on:
  push:
    branches: [main, docker]

jobs:
  build:
    name: 🔍 Build playwright image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: playwright-image:latest
          outputs: type=docker,dest=/tmp/playwright-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-image
          path: /tmp/playwright-image.tar

  test:
    name: 🧪 Test (${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1,2,3,4,5]
        shardTotal: [5]

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: playwright-image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/playwright-image.tar
          docker image ls -a

      - name: Run Playwright tests in container
        run: |
          docker run -e CI=true -e LABEL=bwin.es playwright-image:latest npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: copy report
        if: always()
        run: |
          CONTAINER_ID=$(docker ps -aqf ancestor=playwright-image)
          docker cp $CONTAINER_ID:/usr/src/app/blob-report .

      - uses: actions/upload-artifact@v2
        if: always()      
        with:
          name: all-blob-reports
          path: blob-report
          retention-days: 1


  create-report:
    name: 📔 Create test report
    if: always()
    needs: [test]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v2
      with:
        name: all-blob-reports
        path: all-blob-reports

    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./all-blob-reports 

    - name: Debug
      run: |
        ls -R
        cd playwright-report
        ls
        find .

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: html-playwright-report
        path: playwright-report
        retention-days: 7

    - name: Install gh-pages
      run: npm install -g gh-pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
      run: gh-pages -d playwright-report -b docker       

  # deploy-gh-pages:
  #   name: 🚀 Deploy to GitHub Pages
  #   runs-on: ubuntu-latest
  #   needs: [create-report]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'

  #     - name: Install gh-pages
  #       run: npm install -g gh-pages

  #     - name: Deploy to GitHub Pages
  #       run: gh-pages -d playwright-report -b docker
