name: Build and Run Docker Image

on:
  push:
    branches: [main, docker]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: playwright-image:latest
          outputs: type=docker,dest=/tmp/playwright-image.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-image
          path: /tmp/playwright-image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1]
        shardTotal: [1]

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: playwright-image
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/playwright-image.tar

      - 
        name: Run Playwright tests in container
        run: |
          REPORT_PATH=$(docker run -e CI=true playwright-image:latest npm test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} | tee /tmp/report-path.txt)
          echo "Report path within the container: $REPORT_PATH"
          docker cp $(docker ps -q -l):$REPORT_PATH /tmp

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: blob-report
          path: /tmp/blob-report
