name: Parallel Playwright Tests

on:
  push:
    branches: [ main, docker ]
  pull_request:
    branches: [ main, docker ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image-id: ${{ steps.set-image-id.outputs.image-id }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Build Docker image
      id: set-image-id
      run: |
        DOCKER_IMAGE_ID=$(docker build -q -t playwright-docker-image:latest .)
        echo "image-id=$DOCKER_IMAGE_ID" >> $GITHUB_ENV

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    container:
      image: ${{ needs.build.outputs.image-id }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Playwright tests in parallel
      run: |
        docker run ${{ needs.build.outputs.image-id }} npm test
